### ISSUE TITLE
Use it with webrtc_ros

### ISSUE THREAD

**Issue by Daemonised** [Rehab-Robotics-Lab/LilFloSystem#157]
Hey guys,

i have a school project about control robot in real time and i have some questions about the repo:

-What codes can we use in the repo? What is really interesting me is the web application and the launch file in the repo flo_web. For the web application, my goal is to make some test, if everything works fine for me, i do my own web app. 

-About the launch file in flo_web, is it this file we need to launch to make a connection between the webrtc_ros and the web app? We discuss about it in the issue of the webrtc_ros.

Thanks you for your answer, this is really good work.

**Comment by mjsobrep** [comment]
Hey @Daemonised 

- For a school project you should be able to use everything here without concern. The only real worries would be if you were developing something commercial
- The webrtc_ros stack is launched in [webrtc.launch](https://github.com/Rehab-Robotics-Lab/LilFloSystem/blob/master/flo_telepresence/launch/webrtc.launch).
- The best way to trace down what is going on is to start in the [central bringup launch file](https://github.com/Rehab-Robotics-Lab/LilFloSystem/blob/master/flo_core/launch/flo_bringup.launch), that will shed a lot of light on how the pieces interact. 
- You may be able to try a lot of it out without a real robot using the [sim launcher](https://github.com/Rehab-Robotics-Lab/LilFloSystem/blob/master/flo_core/launch/flo_sim.launch)

Let me know if that all helps out or if you have some more questions!

**Comment by Daemonised** [comment]
Hey,

Thanks for let met use it, i really appreciate it.

- I feel like there is a lot of think in the [central bringup launch file](https://github.com/Rehab-Robotics-Lab/LilFloSystem/blob/master/flo_core/launch/flo_bringup.launch) that will not really help me to just send a stream and control the robot. For just sending data over datachannel and a stream video, i can only use the [webrtc.launch](https://github.com/Rehab-Robotics-Lab/LilFloSystem/blob/master/flo_telepresence/launch/webrtc.launch)? 

- also i have launch the [webrtc.launch](https://github.com/Rehab-Robotics-Lab/LilFloSystem/blob/master/flo_telepresence/launch/webrtc.launch), it's working fine.

-I have also launch the [web_app.launch](https://github.com/Rehab-Robotics-Lab/LilFloSystem/blob/master/flo_web/launch/web_app.launch) to make it connect to node.js website. is it the correct way to do it? If this is correct i just need to change the ip to make it connect to an outside web app?

- For the simulation i need to check more.

Thanks.

**Comment by mjsobrep** [comment]
Yeah, unfortunately I don't think it will be easy to just run a single file and make it all work. You will also need multiple servers setup and the routers. You might want to try out the stuff from Freedom Robotics. They have a commercial solution that is plug and play.
